Repository pagopa/io-app-design-system, pull requests merged in 2023-09, with the labels that each got.

#60 [IOAPPFD0-143] Add new pictograms needed for ITWallet flow
  example/src/pages/Icons.tsx
  example/src/pages/Pictograms.tsx
  src/components/pictograms/Pictogram.tsx
  src/components/pictograms/svg/PictogramAccessDenied.tsx
  src/components/pictograms/svg/PictogramAttention.tsx
  src/components/pictograms/svg/PictogramCharity.tsx
  src/components/pictograms/svg/PictogramEmpty.tsx
  src/components/pictograms/svg/PictogramEmptyArchive.tsx
  src/components/pictograms/svg/PictogramFatalError.tsx
  src/components/pictograms/svg/PictogramFeedback.tsx
  src/components/pictograms/svg/PictogramITWallet.tsx
  src/components/pictograms/svg/PictogramIdentity.tsx
  src/components/pictograms/svg/PictogramIdentityAdd.tsx
  src/components/pictograms/svg/PictogramIdentityCheck.tsx
  src/components/pictograms/svg/PictogramIdentityRefresh.tsx
  src/components/pictograms/svg/PictogramPasscode.tsx
  src/components/pictograms/svg/PictogramStopSecurity.tsx
  src/components/pictograms/svg/PictogramSuccess.tsx
  src/components/pictograms/svg/PictogramTime.tsx
  src/components/pictograms/svg/PictogramTrash.tsx
  src/components/pictograms/svg/PictogramUpdateOS.tsx
  src/components/pictograms/svg/originals/PictogramAccessDenied.svg
  src/components/pictograms/svg/originals/PictogramAttention.svg
  src/components/pictograms/svg/originals/PictogramCharity.svg
  src/components/pictograms/svg/originals/PictogramEmpty.svg
  src/components/pictograms/svg/originals/PictogramEmptyArchive.svg
  src/components/pictograms/svg/originals/PictogramFatalError.svg
  src/components/pictograms/svg/originals/PictogramFeedback.svg
  src/components/pictograms/svg/originals/PictogramITWallet.svg
  src/components/pictograms/svg/originals/PictogramIdentity.svg
  src/components/pictograms/svg/originals/PictogramIdentityAdd.svg
  src/components/pictograms/svg/originals/PictogramIdentityCheck.svg
  src/components/pictograms/svg/originals/PictogramIdentityRefresh.svg
  src/components/pictograms/svg/originals/PictogramPasscode.svg
  src/components/pictograms/svg/originals/PictogramStopSecurity.svg
  src/components/pictograms/svg/originals/PictogramSuccess.svg
  src/components/pictograms/svg/originals/PictogramTime.svg
  src/components/pictograms/svg/originals/PictogramTrash.svg
  src/components/pictograms/svg/originals/PictogramUpdateOS.svg
Labels: Assets

#63 [IOAPPFD0-145] Add the new `PictogramBleed` component
  example/src/components/AssetViewerBox.tsx
  example/src/pages/Advice.tsx
  example/src/pages/Pictograms.tsx
  src/components/banner/Banner.tsx
  src/components/banner/__test__/__snapshots__/banner.test.tsx.snap
  src/components/banner/__test__/banner.test.tsx
  src/components/pictograms/Pictogram.tsx
  src/components/pictograms/svg/PictogramBleedCharity.tsx
  src/components/pictograms/svg/PictogramBleedFeedback.tsx
  src/components/pictograms/svg/PictogramBleedHelp.tsx
  src/components/pictograms/svg/PictogramBleedITWallet.tsx
  src/components/pictograms/svg/PictogramDonation.tsx
  src/components/pictograms/svg/PictogramFocusOn.tsx
  src/components/pictograms/svg/PictogramHelp.tsx
  src/components/pictograms/svg/PictogramSetup.tsx
  src/components/pictograms/svg/originals/PictogramBleedCharity.svg
  src/components/pictograms/svg/originals/PictogramBleedFeedback.svg
  src/components/pictograms/svg/originals/PictogramBleedHelp.svg
  src/components/pictograms/svg/originals/PictogramBleedITWallet.svg
  src/components/pictograms/svg/originals/PictogramFocusOn.svg
  src/components/pictograms/svg/originals/PictogramHelp.svg
Labels: Assets

#69 [IOAPPFD0-147] Add new pictograms and icons
  src/components/icons/Icon.tsx
  src/components/icons/svg/IconDialpad.tsx
  src/components/icons/svg/IconKey.tsx
  src/components/icons/svg/IconNotification.tsx
  src/components/icons/svg/IconOption.tsx
  src/components/icons/svg/originals/IconDialpad.svg
  src/components/icons/svg/originals/IconKey.svg
  src/components/icons/svg/originals/IconNotification.svg
  src/components/icons/svg/originals/IconOption.svg
  src/components/pictograms/Pictogram.tsx
  src/components/pictograms/svg/PictogramBleedCie.tsx
  src/components/pictograms/svg/PictogramBleedFeature.tsx
  src/components/pictograms/svg/PictogramBleedSecurity.tsx
  src/components/pictograms/svg/PictogramCie.tsx
  src/components/pictograms/svg/PictogramFeature.tsx
  src/components/pictograms/svg/PictogramSecurity.tsx
  src/components/pictograms/svg/originals/PictogramBleedCie.svg
  src/components/pictograms/svg/originals/PictogramBleedFeature.svg
  src/components/pictograms/svg/originals/PictogramBleedSecurity.svg
  src/components/pictograms/svg/originals/PictogramCie.svg
  src/components/pictograms/svg/originals/PictogramFeature.svg
  src/components/pictograms/svg/originals/PictogramSecurity.svg
Labels: Assets

#62 [IOAPPFD0-144] Add the new `IconContained` component
  example/src/pages/Icons.tsx
  src/components/icons/Icon.tsx
  src/components/icons/IconContained.tsx
  src/components/icons/index.tsx
  src/components/icons/svg/IconTransactions.tsx
  src/components/icons/svg/IconTransactionsBoxed.tsx
  src/components/icons/svg/originals/IconTransactions.svg
  src/components/icons/svg/originals/IconTransactionsBoxed.svg
  src/core/IOStyles.ts
Labels: Assets, Foundation

#76 feat: [SIW-499] Add credentials catalog icons
  src/components/icons/Icon.tsx
  src/components/icons/svg/IconDisabilityCard.tsx
  src/components/icons/svg/IconDriverLicense.tsx
  src/components/icons/svg/IconHealthCard.tsx
  src/components/icons/svg/originals/IconDisabilityCard.svg
  src/components/icons/svg/originals/IconDriverLicense.svg
  src/components/icons/svg/originals/IconHealthCard.svg
Labels: Assets

#74 [IOAPPFD0-150] Add the new `IOPictogramsObject` set
  example/src/pages/Advice.tsx
  example/src/pages/Pictograms.tsx
  src/components/featureInfo/FeatureInfo.tsx
  src/components/featureInfo/index.tsx
  src/components/index.tsx
  src/components/pictograms/Pictogram.tsx
  src/components/pictograms/svg/PictogramIBANCard.tsx
  src/components/pictograms/svg/PictogramObjClock.tsx
  src/components/pictograms/svg/PictogramObjFlyingMessage.tsx
  src/components/pictograms/svg/PictogramObjFollowMessage.tsx
  src/components/pictograms/svg/PictogramObjIbanCard.tsx
  src/components/pictograms/svg/PictogramObjKey.tsx
  src/components/pictograms/svg/PictogramObjManual.tsx
  src/components/pictograms/svg/PictogramObjTrash.tsx
  src/components/pictograms/svg/originals/PictogramIBANCard.svg
  src/components/pictograms/svg/originals/PictogramObjClock.svg
  src/components/pictograms/svg/originals/PictogramObjFlyingMessage.svg
  src/components/pictograms/svg/originals/PictogramObjFollowMessage.svg
  src/components/pictograms/svg/originals/PictogramObjIbanCard.svg
  src/components/pictograms/svg/originals/PictogramObjKey.svg
  src/components/pictograms/svg/originals/PictogramObjManual.svg
  src/components/pictograms/svg/originals/PictogramObjTrash.svg
Labels: Assets

#80 [IOAPPFD0-154] Fix UI regressions affecting `Button…` and `LabelLink` components
  example/src/pages/Buttons.tsx
  src/components/buttons/ButtonLink.tsx
  src/components/buttons/ButtonOutline.tsx
  src/components/buttons/ButtonSolid.tsx
  src/components/typography/ButtonText.tsx
  src/components/typography/LabelLink.tsx
  src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
Labels: bug

#84 Make the buttons contained in the new `FooterWithButtons` full width by default
  example/src/pages/FooterWithButton.tsx
  src/components/layout/BlockButtons.tsx
Labels: enhancement

#86 Remove unused `ModuleIDP` prop
  example/src/pages/Modules.tsx
  src/components/modules/ModuleIDP.tsx
Labels: bug

#87 Export types of `ListItemSwitch` and `ModulePaymentNotice` components
  src/components/listitems/ListItemSwitch.tsx
  src/components/modules/ModulePaymentNotice.tsx
Labels: enhancement
