Repository pagopa/io-app-design-system, pull requests merged in 2024-07, with the labels that each got.

#296 [IOAPPX-330] Allow font scaling to all the typographic styles when experimental DS is on
  example/src/pages/ListItem.tsx
  src/components/Advice/__test__/__snapshots__/advice.test.tsx.snap
  src/components/alert/Alert.tsx
  src/components/badge/Badge.tsx
  src/components/badge/__test__/__snapshots__/badge.test.tsx.snap
  src/components/banner/__test__/__snapshots__/banner.test.tsx.snap
  src/components/buttons/ButtonSolid.tsx
  src/components/buttons/__test__/__snapshots__/button.test.tsx.snap
  src/components/listitems/ListItemAmount.tsx
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
  src/components/modules/ModuleAttachment.tsx
  src/components/modules/ModuleCheckout.tsx
  src/components/modules/ModuleIDP.tsx
  src/components/modules/PressableModuleBase.tsx
  src/components/numberpad/__test__/__snapshots__/NumberPad.test.tsx.snap
  src/components/toast/__tests__/__snapshots__/ToastNotification.test.tsx.snap
  src/components/typography/Body.tsx
  src/components/typography/BodyMonospace.tsx
  src/components/typography/ButtonText.tsx
  src/components/typography/Caption.tsx
  src/components/typography/Chip.tsx
  src/components/typography/H1.tsx
  src/components/typography/H2.tsx
  src/components/typography/H3.tsx
  src/components/typography/H4.tsx
  src/components/typography/H5.tsx
  src/components/typography/H6.tsx
  src/components/typography/Label.tsx
  src/components/typography/LabelLink.tsx
  src/components/typography/LabelSmall.tsx
  src/components/typography/LabelSmallAlt.tsx
  src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
  src/core/IOStyles.ts
Labels: Foundation, a11y

#297 [IOAPPX-334] Add `alignItems` prop to `HStack` and `VStack` components
  example/src/pages/Layout.tsx
  src/components/stack/Stack.tsx
  src/core/IOSpacing.ts
Labels: Foundation

#302 Decrease `H4` and `H3` font sizes (legacy version)
  src/components/numberpad/__test__/__snapshots__/NumberPad.test.tsx.snap
  src/components/typography/H3.tsx
  src/components/typography/H4.tsx
  src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
Labels: Foundation

#308 [IOPID-2011] integrate setting pictogram
  scripts/pictograms_timestamp.txt
  src/components/pictograms/Pictogram.tsx
  src/components/pictograms/svg/PictogramBleedSettings.tsx
  src/components/pictograms/svg/PictogramSettings.tsx
  src/components/pictograms/svg/originals/PictogramBleedSettings.svg
  src/components/pictograms/svg/originals/PictogramSettings.svg
Labels: Assets

#307 [IOAPPX-342] Update the icon set with new entries
  scripts/icons_timestamp.txt
  src/components/icons/Icon.tsx
  src/components/icons/svg/IconBonusFilled.tsx
  src/components/icons/svg/IconCreditCardFilled.tsx
  src/components/icons/svg/IconDisabilityCard.tsx
  src/components/icons/svg/IconDriverLicense.tsx
  src/components/icons/svg/IconHeartEmpty.tsx
  src/components/icons/svg/IconHeartFilled.tsx
  src/components/icons/svg/IconHeartOff.tsx
  src/components/icons/svg/IconStarOff.tsx
  src/components/icons/svg/originals/IconBonusFilled.svg
  src/components/icons/svg/originals/IconCreditCardFilled.svg
  src/components/icons/svg/originals/IconDisabilityCard.svg
  src/components/icons/svg/originals/IconDriverLicense.svg
  src/components/icons/svg/originals/IconHeartOff.svg
  src/components/icons/svg/originals/IconStarOff.svg
Labels: Foundation

#309 [IOAPPX-351] Refactor `IOSpacing` to avoid repeated values
  src/core/IOSpacing.ts
Labels: Foundation

#317 [IOAPPX-359] Remove mandatory a11y props from some `ListItem…` components
  src/components/listitems/ListItemAction.tsx
  src/components/listitems/ListItemInfoCopy.tsx
  src/components/listitems/ListItemNavAlert.tsx
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
Labels: a11y

#320 [IOAPPX-360] Remove almost all the legacy pictograms not referenced anymore
  src/components/pictograms/Pictogram.tsx
  src/components/pictograms/svg/PictogramAbacus.tsx
  src/components/pictograms/svg/PictogramAirBaloon.tsx
  src/components/pictograms/svg/PictogramAirship.tsx
  src/components/pictograms/svg/PictogramBaloons.tsx
  src/components/pictograms/svg/PictogramBeerMug.tsx
  src/components/pictograms/svg/PictogramEmailToValidate.tsx
  src/components/pictograms/svg/PictogramEmailValidation.tsx
  src/components/pictograms/svg/PictogramError.tsx
  src/components/pictograms/svg/PictogramFireworks.tsx
  src/components/pictograms/svg/PictogramHeart.tsx
  src/components/pictograms/svg/PictogramHourglass.tsx
  src/components/pictograms/svg/PictogramInProgress.tsx
  src/components/pictograms/svg/PictogramInbox.tsx
  src/components/pictograms/svg/PictogramMessages.tsx
  src/components/pictograms/svg/PictogramNotAvailable.tsx
  src/components/pictograms/svg/PictogramPiggyBank.tsx
  src/components/pictograms/svg/PictogramPin.tsx
  src/components/pictograms/svg/PictogramPlaces.tsx
  src/components/pictograms/svg/PictogramPuzzle.tsx
  src/components/pictograms/svg/PictogramQuestion.tsx
  src/components/pictograms/svg/PictogramSearch.tsx
  src/components/pictograms/svg/PictogramSms.tsx
  src/components/pictograms/svg/PictogramTeaBreak.tsx
  src/components/pictograms/svg/PictogramTimeout.tsx
  src/components/pictograms/svg/PictogramUmbrella.tsx
  src/components/pictograms/svg/PictogramUnrecognized.tsx
  src/components/pictograms/svg/PictogramUploadFile.tsx
  src/components/pictograms/svg/originals/PictogramAbacus.svg
  src/components/pictograms/svg/originals/PictogramAirBaloon.svg
  src/components/pictograms/svg/originals/PictogramAirship.svg
  src/components/pictograms/svg/originals/PictogramBaloons.svg
  src/components/pictograms/svg/originals/PictogramBeerMug.svg
  src/components/pictograms/svg/originals/PictogramEmailToValidate.svg
  src/components/pictograms/svg/originals/PictogramEmailValidation.svg
  src/components/pictograms/svg/originals/PictogramError.svg
  src/components/pictograms/svg/originals/PictogramFireworks.svg
  src/components/pictograms/svg/originals/PictogramHeart.svg
  src/components/pictograms/svg/originals/PictogramHourglass.svg
  src/components/pictograms/svg/originals/PictogramInProgress.svg
  src/components/pictograms/svg/originals/PictogramInbox.svg
  src/components/pictograms/svg/originals/PictogramMessages.svg
  src/components/pictograms/svg/originals/PictogramNotAvailable.svg
  src/components/pictograms/svg/originals/PictogramPiggyBank.svg
  src/components/pictograms/svg/originals/PictogramPin.svg
  src/components/pictograms/svg/originals/PictogramPlaces.svg
  src/components/pictograms/svg/originals/PictogramPuzzle.svg
  src/components/pictograms/svg/originals/PictogramQuestion.svg
  src/components/pictograms/svg/originals/PictogramSearch.svg
  src/components/pictograms/svg/originals/PictogramSms.svg
  src/components/pictograms/svg/originals/PictogramTeaBreak.svg
  src/components/pictograms/svg/originals/PictogramTimeout.svg
  src/components/pictograms/svg/originals/PictogramUmbrella.svg
  src/components/pictograms/svg/originals/PictogramUnrecognized.svg
  src/components/pictograms/svg/originals/PictogramUploadFile.svg
Labels: Foundation
