Repository pagopa/io-app-design-system, pull requests merged in 2024-06, with the labels that each got.

#278 [IOPID-1531] fix radio button accessibility on android
  src/components/listitems/ListItemRadio.tsx
Labels: bug

#283 [IOAPPX-315] Update `Search` pictograms
  scripts/pictograms_timestamp.txt
  src/components/pictograms/svg/PictogramBleedSearch.tsx
  src/components/pictograms/svg/PictogramSearchLens.tsx
  src/components/pictograms/svg/originals/PictogramBleedSearch.svg
  src/components/pictograms/svg/originals/PictogramSearchLens.svg
Labels: Foundation

#285 [IOAPPX-318] Add `contrast` variant and optional `backgroundColor` prop to `HeaderSecondLevel`
  example/src/navigation/navigator.tsx
  example/src/navigation/params.ts
  example/src/navigation/routes.ts
  example/src/pages/HeaderSecondLevelCustomBackground.tsx
  src/components/layout/HeaderSecondLevel.tsx
Labels: enhancement

#284 [IOPID-1899] `NumberPad` optimization
  example/src/pages/NumberPad.tsx
  package.json
  src/components/numberpad/NumberButton.tsx
  src/components/numberpad/NumberPad.tsx
  src/components/numberpad/__test__/NumberPad.test.tsx
  src/components/numberpad/__test__/__snapshots__/NumberPad.test.tsx.snap
  src/utils/types.ts
  stories/components/numberpad/NumberPad.stories.tsx
Labels: documentation, enhancement, don't merge ✋

#293 [IOAPPX-326] Fix bug on Android when using `SemiBold` font weight
  .storybook/preview-head.html
  example/src/pages/Advice.tsx
  example/src/pages/Alert.tsx
  example/src/pages/Buttons.tsx
  example/src/pages/Colors.tsx
  example/src/pages/Icons.tsx
  example/src/pages/ListItem.tsx
  example/src/pages/Logos.tsx
  example/src/pages/Modules.tsx
  example/src/pages/Pictograms.tsx
  src/components/badge/Badge.tsx
  src/components/banner/__test__/__snapshots__/banner.test.tsx.snap
  src/components/buttons/__test__/__snapshots__/button.test.tsx.snap
  src/components/layout/HeaderSecondLevel.tsx
  src/components/listitems/ListItemAction.tsx
  src/components/listitems/ListItemAmount.tsx
  src/components/listitems/ListItemNavAlert.tsx
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
  src/components/modules/ModuleIDP.tsx
  src/components/modules/ModulePaymentNotice.tsx
  src/components/numberpad/__test__/__snapshots__/NumberPad.test.tsx.snap
  src/components/otpInput/BoxedInput.tsx
  src/components/switch/SwitchLabel.tsx
  src/components/tag/Tag.tsx
  src/components/textInput/TextInputBase.tsx
  src/components/typography/Body.tsx
  src/components/typography/ButtonText.tsx
  src/components/typography/Chip.tsx
  src/components/typography/H1.tsx
  src/components/typography/H2.tsx
  src/components/typography/H3.tsx
  src/components/typography/H4.tsx
  src/components/typography/H5.tsx
  src/components/typography/H6.tsx
  src/components/typography/Hero.tsx
  src/components/typography/Label.tsx
  src/components/typography/LabelHeader.tsx
  src/components/typography/LabelLink.tsx
  src/components/typography/LabelSmall.tsx
  src/components/typography/LabelSmallAlt.tsx
  src/components/typography/README.md
  src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
  src/components/typography/markdown/MdH2.tsx
  src/components/typography/markdown/MdH4.tsx
  src/utils/fonts.ts
Labels: bug

#295 [IOAPPX-331] Add legacy `blue` to `Pictogram`, when experimental DS is off
  src/core/IOColors.ts
Labels: Foundation
