Repository pagopa/io-app-design-system, pull requests merged in 2024-08, with the labels that each got.

#322 [IOAPPX-362] Change `Label…` default weight to Semibold + Fix autocomplete of `IOText` when using `font` prop
  src/components/typography/Label.tsx
  src/components/typography/LabelMini.tsx
  src/components/typography/LabelSmall.tsx
  src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
  src/utils/fonts.ts
Labels: Foundation

#324 [IOAPPX-366] Refine `entering/exiting` transition applied to `ToastNotification`
  src/components/toast/ToastProvider.tsx
Labels: enhancement

#323 [IOAPPX-365] Add `enableDiscreteTransition` to `HeaderSecondLevel` to allow transition even if `triggerOffset` is not set
  example/src/navigation/navigator.tsx
  example/src/navigation/params.ts
  example/src/navigation/routes.ts
  example/src/pages/HeaderSecondLevelDiscreteTransition.tsx
  example/src/pages/HeaderSecondLevelScreenDiscreteTransitionCustomBg.tsx
  src/components/layout/HeaderSecondLevel.tsx
  src/core/IOAnimations.ts
Labels: enhancement

#326 [IOPID-2107] Adjust TextInput accessibility behavior
  src/components/textInput/TextInputBase.tsx
Labels: bug, a11y

#327 [IOPID-2107] - A11Y TextInputBase accessibility improvement
  src/components/textInput/TextInputBase.tsx
  src/components/textInput/TextInputValidation.tsx
Labels: bug, a11y

#328 [IOPID-2111] Fix `ListItemInfo` screen reader behaviour
  src/components/badge/Badge.tsx
  src/components/badge/__test__/__snapshots__/badge.test.tsx.snap
  src/components/listitems/ListItemInfo.tsx
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
Labels: bug, a11y
