Repository pagopa/io-app-design-system, pull requests merged in 2024-05, with the labels that each got.

#252 chore: Expose `autoFocus` `prop` on `OTPInput`
  example/src/pages/OTPInput.tsx
  src/components/otpInput/OTPInput.tsx
Labels: enhancement

#257 [IOPID-1825] Add accessibility label to idp module component
  src/components/modules/ModuleIDP.tsx
Labels: a11y

#261 [IOAPPX-294] Add `activate` and `reactivate` bleed pictograms
  scripts/pictograms_timestamp.txt
  src/components/pictograms/Pictogram.tsx
  src/components/pictograms/svg/PictogramBleedActivate.tsx
  src/components/pictograms/svg/PictogramBleedPayments.tsx
  src/components/pictograms/svg/PictogramBleedReactivate.tsx
  src/components/pictograms/svg/PictogramHello.tsx
  src/components/pictograms/svg/PictogramPayments.tsx
  src/components/pictograms/svg/originals/PictogramBleedActivate.svg
  src/components/pictograms/svg/originals/PictogramBleedPayments.svg
  src/components/pictograms/svg/originals/PictogramBleedReactivate.svg
  src/components/pictograms/svg/originals/PictogramComunicationProblem.svg
  src/components/pictograms/svg/originals/PictogramEventClose.svg
  src/components/pictograms/svg/originals/PictogramHello.svg
  src/components/pictograms/svg/originals/PictogramPayments.svg
Labels: Foundation

#267 [IOAPPX-298] Fix the value of the H4 line height
  src/components/typography/H4.tsx
  src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
Labels: Foundation

#258 [IOAPPX-289] Delete unused colors from `IOColors`
  example/src/components/AssetViewerBox.tsx
  src/core/IOColors.ts
Labels: Foundation

#243 [IOAPPX-283] Deprecate `GradientScrollView` for `IOScrollView`
  example/src/navigation/navigator.tsx
  package.json
  src/components/layout/GradientBottomActions.tsx
  src/components/layout/GradientScrollView.tsx
  src/components/layout/index.tsx
  yarn.lock
Labels: enhancement

#268 chore: [IOBP-641] Add `ListItemHeader` a11y role as heading
  src/components/listitems/ListItemHeader.tsx
Labels: a11y

#269 [IOAPPX-301] Add the new `satispay` payment logo (both small and big)
  src/components/logos/LogoPayment.tsx
  src/components/logos/LogoPaymentExt.tsx
  src/components/logos/svg/LogoPaymentExtSatispay.tsx
  src/components/logos/svg/LogoPaymentSatispay.tsx
  src/components/logos/svg/originals/LogoPaymentExtSatispay.svg
  src/components/logos/svg/originals/LogoPaymentSatispay.svg
Labels: Foundation
