Repository pagopa/io-app-design-system, pull requests merged in 2025-02, with the labels that each got.

#389 [IOAPPX-477] Fix `IconProductIOAppBlueBg` icon
  src/components/icons/svg/IconProductIOAppBlueBg.tsx
  src/components/icons/svg/originals/IconProductIOAppBlueBg.svg
Labels: bug, Foundation

#394 refactor: [IOBP-1163] Apply ignore accessibility flag
  src/components/layout/HeaderSecondLevel.tsx
Labels: a11y

#397 [IOPLT-952] Fix `TextInputValidation` regression
  src/components/textInput/TextInputValidation.tsx
Labels: bug

#402 refactor(Banner): `a11y` replace `View` with `Pressable`
  src/components/banner/Banner.tsx
  src/components/banner/__test__/__snapshots__/banner.test.tsx.snap
Labels: a11y

#406 feat: apply custom accessibility error label
  src/components/textInput/TextInputValidation.tsx
Labels: a11y

#404 chore: [IOPLT-973] Improve markdown related typographic styles
  src/components/typography/markdown/MdH1.tsx
  src/components/typography/markdown/MdH2.tsx
  src/components/typography/markdown/MdH3.tsx
  src/core/IOColors.ts
Labels: Foundation

#405 feat: support for `onBlur` and `onContinue` validation modes in `TextInputValidation` component
  example/src/pages/TextInputs.tsx
  src/components/textInput/TextInputValidation.tsx
Labels: enhancement

#409 fix: [IOPLT-982] Export `a11y` related hooks
  src/index.tsx
Labels: a11y

#411 Remove unused assets
  src/components/icons/svg/IconEmailLegal.tsx
  src/components/icons/svg/originals/IconEmailLegal.svg
  src/components/pictograms/svg/PictogramDonation.tsx
  src/components/pictograms/svg/PictogramGenericError.tsx
  src/components/pictograms/svg/PictogramSetup.tsx
  src/components/pictograms/svg/originals/PictogramDonation.svg
  src/components/pictograms/svg/originals/PictogramGenericError.svg
  src/components/pictograms/svg/originals/PictogramSetup.svg
Labels: Foundation

#416 chore: [IOPAE-1728] Improve accessibility on `SearchInput` component
  src/components/searchInput/SearchInput.tsx
Labels: a11y

#419 chore(Badge): Add `accessible` prop
  src/components/badge/Badge.tsx
Labels: a11y
