Repository pagopa/io-app-design-system, pull requests merged in 2025-03, with the labels that each got.

#421 chore: [IOBP-1186] Add `accessibilityLabel` prop to `RadioItem` type component
  src/components/radio/RadioGroup.tsx
Labels: a11y

#422 fix: [IOBP-1254] Add the correct accessibilityState to the `TabItem`
  src/components/tabs/TabItem.tsx
Labels: a11y

#420 fix: [IOPLT-997] Fix visual issue on dark mode version of `TabItem`
  src/components/tabs/TabItem.tsx
  src/components/tabs/TabNavigation.tsx
Labels: bug

#424 refactor: default hint for a11y label
  src/components/listitems/ListItemRadioWithAmount.tsx
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
Labels: a11y

#425 [IOPLT-968] Add dark mode version to `NumberPad` component
  example/src/pages/NumberPad.tsx
  src/components/codeInput/CodeInput.tsx
  src/components/numberpad/NumberButton.tsx
  src/components/numberpad/NumberPad.tsx
  stories/components/numberpad/NumberPad.stories.tsx
Labels: Dark mode 🌝

#426 feat(TextInput): iban formatter
  example/src/pages/TextInputs.tsx
  src/utils/textInput/index.ts
  src/utils/types.ts
Labels: enhancement

#428 fix(`TextInputBase`): correct counter limit handling
  src/components/textInput/TextInputBase.tsx
Labels: bug

#430 fix: [IOPLT-1026] Add the proper accessibility state to all components in the loading state
  example/src/pages/ListItem.tsx
  example/src/pages/Modules.tsx
  example/src/pages/Selection.tsx
  src/components/listitems/ListItemRadio.tsx
  src/components/listitems/ListItemTransaction.tsx
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
  src/components/modules/ModuleAttachment.tsx
  src/components/modules/ModuleCheckout.tsx
  src/components/modules/ModuleCredential.tsx
  src/components/modules/ModuleNavigation.tsx
  src/components/modules/ModulePaymentNotice.tsx
  src/components/modules/ModuleStatic.tsx
Labels: a11y

#432 fix: [IOPLT-1028] Add alternative `accessibilityRole` to `Banner`, `FeatureInfo` and all the `asLink` typographic styles
  example/src/pages/Advice.tsx
  src/components/banner/Banner.tsx
  src/components/featureInfo/FeatureInfo.tsx
  src/components/typography/Body.tsx
  src/components/typography/BodySmall.tsx
  src/components/typography/IOText.tsx
  src/components/typography/LabelMini.tsx
Labels: Foundation, a11y

#427 feat: [IOPLT-966, IOPLT-991] Add the new `IOSkeleton` component to remove the `rn-placeholder` dependency
  example/package.json
  example/src/navigation/navigator.tsx
  example/src/navigation/params.ts
  example/src/navigation/routes.ts
  example/src/pages/Skeleton.tsx
  example/yarn.lock
  package.json
  src/components/index.tsx
  src/components/listitems/ListItemRadio.tsx
  src/components/listitems/ListItemTransaction.tsx
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
  src/components/modules/ModuleAttachment.tsx
  src/components/modules/ModuleCheckout.tsx
  src/components/modules/ModuleCredential.tsx
  src/components/modules/ModuleNavigation.tsx
  src/components/modules/ModulePaymentNotice.tsx
  src/components/skeleton/IOSkeleton.tsx
  src/components/skeleton/index.tsx
  src/core/IOColors.ts
  yarn.lock
Labels: a11y, Dark mode 🌝

#434 chore: adjust `ModuleCheckout` a11y label
  src/components/modules/ModuleCheckout.tsx
Labels: a11y

#435 refactor(`IOSkeleton`): replace `reanimated` with native `Animated` APIs
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
  src/components/skeleton/IOSkeleton.tsx
Labels: enhancement

#438 chore: [IOPLT-967] Add dark mode support to `OTPInput`
  src/components/otpInput/BoxedInput.tsx
  src/components/otpInput/OTPInput.tsx
  src/core/IOColors.ts
Labels: Dark mode 🌝

#440 chore: [IOPLT-1035] Refine both light/dark modes of the `Toast` component
  src/components/toast/ToastNotification.tsx
  src/components/toast/__tests__/__snapshots__/ToastNotification.test.tsx.snap
Labels: Dark mode 🌝

#441 chore: [IOPLT-971] Improve accessibility and performance of the loaders + Add support for dark mode
  example/src/pages/Loaders.tsx
  src/components/listitems/ListItemSwitch.tsx
  src/components/loadingSpinner/LoadingSpinner.tsx
  src/components/modules/ModuleAttachment.tsx
  src/components/modules/ModuleCredential.tsx
  src/components/otpInput/OTPInput.tsx
  src/components/progressLoader/ProgressLoader.tsx
Labels: a11y, Dark mode 🌝

#437 chore: [IOPLT-933] Upgrade example app RN version to `0.75.4`
  .github/actions/setup/action.yml
  .gitignore
  .storybook/manager.ts
  .yarn/plugins/@yarnpkg/plugin-after-install.cjs
  .yarn/releases/yarn-3.6.4.cjs
  .yarnrc
  .yarnrc.yml
  __mocks__/react-native/Libraries/EventEmitter/RCTDeviceEventEmitter.js
  babel.config.js
  example/.gitignore
  example/.yarnrc.yml
  example/Gemfile
  example/Gemfile.lock
  example/android/app/build.gradle
  example/android/app/src/debug/AndroidManifest.xml
  example/android/app/src/debug/java/com/exampleapp/ReactNativeFlipper.java
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/java/com/exampleapp/MainActivity.java
  example/android/app/src/main/java/com/exampleapp/MainActivity.kt
  example/android/app/src/main/java/com/exampleapp/MainApplication.java
  example/android/app/src/main/java/com/exampleapp/MainApplication.kt
  example/android/app/src/main/res/drawable/rn_edit_text_material.xml
  example/android/app/src/release/java/com/exampleapp/ReactNativeFlipper.java
  example/android/build.gradle
  example/android/gradle.properties
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/android/gradlew
  example/android/gradlew.bat
  example/android/settings.gradle
  example/babel.config.js
  example/ios/ExampleApp.xcodeproj/project.pbxproj
  example/ios/ExampleApp/AppDelegate.mm
  example/ios/ExampleApp/Info.plist
  example/ios/ExampleApp/PrivacyInfo.xcprivacy
  example/ios/Podfile
  example/ios/Podfile.lock
  example/metro.config.js
  example/package.json
  example/react-native.config.js
  example/tsconfig.json
  example/yarn.lock
  jestSetup.js
  package.json
  src/components/buttons/__test__/__snapshots__/button.test.tsx.snap
  src/components/claimsSelector/__test__/__snapshots__/ClaimsSelector.test.tsx.snap
  src/components/listitems/ListItemInfoCopy.tsx
  src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
  src/components/numberpad/__test__/__snapshots__/NumberPad.test.tsx.snap
  src/components/toast/__tests__/__snapshots__/ToastNotification.test.tsx.snap
  src/functions/haptic-feedback/hapticFeedback.ts
  stories/addons/ExperimentalDsToggle.tsx
  stories/utils.tsx
  yarn.lock
Labels: dependencies

#445 fix: [IOPLT-933] Fix iOS related files (`Podfile.lock`, `*.pbxproj`) after `ExampleApp` upgrade to `0.75`
  example/ios/ExampleApp.xcodeproj/project.pbxproj
  example/ios/Podfile.lock
Labels: bug

#443 chore: [IOPLT-1045] Update `reanimated` to `3.17.1`
  example/ios/ExampleApp.xcodeproj/project.pbxproj
  example/ios/Podfile.lock
  example/package.json
  example/tsconfig.json
  example/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#448 fix: [IOPLT-933] Fix CLI error when you try to install the library on external repositories
  .github/actions/setup/action.yml
  .github/workflows/checks.yml
  .github/workflows/github-release.yml
  .github/workflows/release-storybook.yml
  .github/workflows/release.yml
  .yarnrc.yml
  example/.yarnrc.yml
  package.json
Labels: bug

#447 fix: [IOPLT-1049] Refactor `Avatar` and `AvatarSearch` to restore the correct behavior
  example/src/pages/Logos.tsx
  src/components/avatar/Avatar.tsx
  src/components/avatar/__test__/__snapshots__/avatar.test.tsx.snap
Labels: bug

#444 chore: [IOPLT-1048] Migrate `BannerErrorState` from main repo + Add dark mode support
  example/src/pages/Advice.tsx
  src/components/banner/Banner.tsx
  src/components/banner/BannerErrorState.tsx
  src/components/banner/__test__/__snapshots__/banner.test.tsx.snap
  src/components/banner/index.tsx
Labels: Dark mode 🌝
